project:
  type: website
  output-dir: docs

lang: en

website:
  title: "Dr Daniel Kapitan | Data-centric AI | Applied AI | Coaching & Mentoring | Masterclasses & Public Speaking"
  site-url: https://kapitan.net
  open-graph: true
  # google-analytics: "G-3N2FL85753"
  search:
    location: sidebar
    type: overlay
  navbar:
    title: false
    logo: /images/@kapitan-logo-redbrick-zilla.png
    pinned: false
    collapse-below: md
  sidebar:
    style: docked  
    collapse-level: 1
    background: light
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dkapitan/
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/dkapitan
        text: "GitHub profile"
    contents:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Anthology of Data Science"
        href: https://anthology-of-data.science
      - text: "Buddhayana"
        href: https://kapitan.net/buddhayana
      - text: "Book an appointment"
        href: appointment/index.qmd
  page-footer:
    left: |
      <br>
      __Chamber of Commerce (KvK):__ 52920259<br>
      __RSIN:__ 850665851<br>
    center: |
      <br>
      __IBAN:__ NL47 KNAB 0259 5268 27<br>
      __Terms & Conditions__ in [Dutch](/resources/230901-algemene-voorwaarden.pdf)<br>
    right: |
      <br>
      Copyright &copy; 2023 Daniel Kapitan<br>
      This website was created with 
      [![](/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)<br>

format:
  html:
    # page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script data-goatcounter="https://dkapitan.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
execute: 
  freeze: auto
