on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - run: quarto add --no-prompt data-intuitive/quarto-d2
      - run: uv pip install --system jupyter
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
