Digitale vaardigheden: {
  shape: rectangle
  label.near: top-left
  Datageletterdheid: {
    shape: rectangle
    label.near: top-left
    AI-geletterdheid: {
      shape: rectangle
      # label.near: top-left
    }
  }
}